services:
  opadviser:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - sleep infinity
    shm_size: 4gb
    volumes:
      - mysql:/var/lib/mysql
      - mysqld:/var/run/mysqld
  db:
    command:
      - --skip-name-resolve
      - --innodb_read_io_threads=28
      - --innodb_write_io_threads=56
      - --innodb_buffer_pool_size=512G
      - --innodb_buffer_pool_load_at_startup=ON
      - --innodb_log_file_size=32M
      - --innodb_log_files_in_group=2
      - --innodb_file_per_table=1
      - --innodb_log_buffer_size=8M
      - --innodb_flush_method=O_DIRECT
      - --innodb_flush_log_at_trx_commit=0
      - --skip-innodb_doublewrite
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - mysqld:/var/run/mysqld
volumes:
  mysql:
  mysqld:
