services:
  opadviser:
    build:
      context: .
      dockerfile: Dockerfile
    cgroup: host
    command:
      - sleep infinity
    privileged: true
    shm_size: 4gb
    volumes:
      - opadviser:/opadviser:delegated
      - mysql:/var/lib/mysql:delegated
volumes:
  opadviser:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/sdc/jeseok/opadviser'
  mysql:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/sdc/jeseok/mysql2'
