services:
  opadviser:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    command:
      - sleep infinity
    shm_size: 4gb
    volumes:
      - /mnt/sdc/jeseok2/opadviser:/opadviser
      - /mnt/sdc/jeseok2/mysql2:/var/lib/mysql
