services:
  opadviser:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - sleep infinity
    shm_size: 4gb
    volumes:
      - /mnt/sdd/jeseok/opadviser:/opadviser
      - /mnt/sdd/jeseok/mysql:/var/lib/mysql
      - /mnt/sdd/jeseok/mysqld:/var/run/mysqld
      - /mnt/sdd/jeseok/sbin:/usr/sbin:ro
  db:
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - /mnt/sdd/jeseok/mysql:/var/lib/mysql
      - /mnt/sdd/jeseok/mysqld:/var/run/mysqld
      - /mnt/sdd/jeseok/sbin:/usr/sbin