services:
  opadviser:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - sleep infinity
  db:
    command:
      - --skip-name-resolve
    environment:
      MYSQL_ROOT_PASSWORD: password
    image: "mysql:5.7"    
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql:delegated
      - /var/run/mysqld:/var/run/mysqld:delegated
