services:
  opadviser:
    build:
      context: .
      dockerfile: Dockerfile-
    cgroup: host
    command:
      - sleep infinity
    privileged: true
    shm_size: 4gb
    volumes:
      - /mnt/sdd/jeseok/opadviser:/opadviser
      - /mnt/sdd/jeseok/mysql:/var/lib/mysql
